### ISSUE TITLE
tangens instead of sinus

### ISSUE THREAD

**Issue by axelbr** [tuw-robotics/tuw_arduino_ros#2]
After reading this [paper](https://info.tuwien.ac.at/mbader/publications/downloads/kaltenegger2016a.pdf), I am curious if the applied motion model in [line 137](https://github.com/tuw-robotics/tuw_arduino_ros/blob/87321b81bd49806f70ca6051b4c5bb011d98a310/tuw_rccar/src/tuw_rccar_node.cpp#L137) is correct. According to the paper, the tangens function should be applied to the angle phi, instead of the sinus function.

**Comment by maxbader** [comment]
Hi Axel

Feel free to update the code but just uncomment the old part unless you are 100% sure.

Thanks

**Comment by geoeo** [comment]
I think sinus is used for an ackermann motion model using wheel encoders, while tangent is used for ackermann motion model using velocity.

For example: In the book "SLAM for mobile robotics" sinus is used in the chapter describing a wheel encoder motion model. While this paper https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5472738 uses the tangent as well.

But im not 100% sure. Tangent and Sinus seem interchangeable at small values
